# 项目基本信息
name = "cf-docker-proxy"
account_id = "${CF_ACCOUNT_ID}"        # ✅ 从 .env 读取
workers_dev = false                    # 生产环境建议关闭 dev 子域名

compatibility_date = "2025-06-15"
main = "dist/main.js"
type = "esm"

# 构建指令
[build]
command = "npm install && npm run build"

# 默认变量（本地预览时）
[vars]
CUSTOM_DOMAIN = "${CUSTOM_DOMAIN}"

# 生产环境配置
[env.production]
name = "cloudflare-docker-proxy"

# 所有映射的加速域名列表（Cloudflare Pages绑定用）
routes = [
  { pattern = "docker.${CUSTOM_DOMAIN}/*", custom_domain = true },
  { pattern = "ghcr.${CUSTOM_DOMAIN}/*", custom_domain = true },
  { pattern = "quay.${CUSTOM_DOMAIN}/*", custom_domain = true },
  { pattern = "gcr.${CUSTOM_DOMAIN}/*", custom_domain = true },
  { pattern = "k8s-gcr.${CUSTOM_DOMAIN}/*", custom_domain = true },
  { pattern = "k8s.${CUSTOM_DOMAIN}/*", custom_domain = true },
  { pattern = "cloudsmith.${CUSTOM_DOMAIN}/*", custom_domain = true }
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "${CUSTOM_DOMAIN}"
